import Link from "next/link"

import {
  LegalList,
  LegalPage,
  LegalSection,
  LegalSubheading,
  Term,
} from "@/components/legal/legal-doc"
import { LEGAL, TERMS_OF_USE } from "@/lib/legal/constants"

export const metadata = {
  title: "Terms of use",
  description:
    "The agreement between you and Aurora Organics, including what the service is and is not.",
}

const TOC = [
  { id: "agreement", label: "The agreement" },
  { id: "not-medical", label: "Not medical advice" },
  { id: "ai", label: "Automated output" },
  { id: "accounts", label: "Your account" },
  { id: "scans", label: "Scans and allowances" },
  { id: "billing", label: "Payment and refunds" },
  { id: "live", label: "Live scan" },
  { id: "acceptable-use", label: "Acceptable use" },
  { id: "content", label: "Your content and our rights" },
  { id: "products", label: "Product recommendations" },
  { id: "termination", label: "Suspension and termination" },
  { id: "warranty", label: "Disclaimer of warranties" },
  { id: "liability", label: "Limitation of liability" },
  { id: "indemnity", label: "Indemnity" },
  { id: "law", label: "Governing law and disputes" },
  { id: "general", label: "General" },
  { id: "changes", label: "Changes" },
]

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of use"
      version={TERMS_OF_USE.version}
      updated={TERMS_OF_USE.updated}
      intro={
        <p>
          These terms govern your use of Aurora Organics. The most important
          section is{" "}
          <Link
            href="#not-medical"
            className="text-foreground underline underline-offset-4"
          >
            section 2
          </Link>
          : this service is cosmetic guidance, not medical care, and it must not
          be used to detect or rule out any medical condition.
        </p>
      }
      toc={TOC}
    >
      <LegalSection id="agreement" title="1. The agreement">
        <p>
          This is an agreement between you and {LEGAL.entity} (
          {LEGAL.tradingName}), of {LEGAL.postalAddress}. By creating an account
          or using the service you accept these terms and our{" "}
          <Link
            href="/privacy"
            className="text-foreground underline underline-offset-4"
          >
            Privacy policy
          </Link>
          . If you do not accept them, do not use the service.
        </p>
        <p>
          You must be at least {LEGAL.minimumAge} years old to use Aurora
          Organics.
        </p>
      </LegalSection>

      <LegalSection id="not-medical" title="2. Not medical advice">
        <p>
          Aurora Organics provides{" "}
          <Term>cosmetic and wellness guidance only</Term>. Read this section
          carefully.
        </p>
        <LegalList>
          <li>
            It is <Term>not a medical device</Term>. It has not been cleared,
            approved, or registered by the FDA, the MHRA, the EMA, or any other
            regulator, and it makes no claim to diagnose, treat, cure, mitigate,
            or prevent any disease or condition.
          </li>
          <li>
            It does <Term>not screen for skin cancer</Term>. It cannot detect
            melanoma, basal cell carcinoma, squamous cell carcinoma, or any
            other malignancy, and it must never be used to decide whether a
            mole, lesion, or changing patch of skin needs attention. If you have
            a mole or lesion that is new, changing, bleeding, or otherwise
            concerning, see a doctor. Do not wait for a scan result.
          </li>
          <li>
            It does not create a doctor-patient relationship, and nothing in it
            is a professional medical opinion.
          </li>
          <li>
            It is not a substitute for professional advice. Never disregard
            medical advice, or delay seeking it, because of something you read
            here.
          </li>
          <li>
            <Term>In an emergency, contact emergency services directly.</Term>
          </li>
        </LegalList>
        <p>
          The assessment bands, dimension notes, and Ayurvedic lean are cosmetic
          descriptions of what is visible in a photograph. They are not
          measurements, not scores, and not clinical findings.
        </p>
      </LegalSection>

      <LegalSection id="ai" title="3. Automated output">
        <p>
          Assessments, chat replies, and recommendations are generated by an
          automated system. That system can be <Term>wrong</Term>. It can
          misread a photograph, miss something visible, describe something that
          is not there, or give guidance that does not suit you.
        </p>
        <p>
          Results vary with lighting, camera quality, angle, makeup, and the
          model version in use. Two scans of the same skin can differ. Treat the
          output as one input among many, use your own judgement, and consult a
          qualified professional for anything that matters.
        </p>
        <p>
          We do not warrant that any output is accurate, complete, current, or
          suitable for you.
        </p>
      </LegalSection>

      <LegalSection id="accounts" title="4. Your account">
        <p>
          You are responsible for your account credentials and for everything
          done through your account. Give us accurate information and keep it up
          to date. Tell us promptly if you think your account has been accessed
          without your permission.
        </p>
        <p>
          One account per person. Do not share an account, and do not let anyone
          else use yours.
        </p>
      </LegalSection>

      <LegalSection id="scans" title="5. Scans and allowances">
        <p>
          Scans are metered. New accounts receive a number of free Starter scans.
          Scans are available at three tiers, Starter, Thinking and Pro, which
          differ in the model used and therefore in cost and depth.
        </p>
        <LegalList>
          <li>Scan allowances have no cash value and are not transferable.</li>
          <li>
            Allowances are tied to the tier they were granted or bought for.
          </li>
          <li>
            If you change tier, any unused allowance on the previous tier is
            converted to the equivalent value on the new tier rather than
            forfeited. If a conversion is not possible, we will refund the
            unused portion.
          </li>
          <li>
            We may adjust the free allowance for new accounts at any time. This
            does not affect allowances already granted to you.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="billing" title="6. Payment and refunds">
        <p>
          Paid scan packs and subscriptions are not yet available. When they
          are, the following applies and prices will be shown before you commit.
        </p>
        <LegalList>
          <li>
            Payments are handled by a third-party payment processor. We do not
            store your card details.
          </li>
          <li>
            Prices are shown inclusive or exclusive of tax as indicated at
            checkout. You are responsible for any taxes not collected by us.
          </li>
          <li>
            Any subscription renews automatically at the interval shown until
            you cancel. You can cancel at any time, effective at the end of the
            current billing period.
          </li>
          <li>
            <Term>Refunds.</Term> If you are a consumer in the UK or EU you have
            a statutory right to cancel within 14 days of purchase. Because
            scans are digital content supplied immediately, that right is
            reduced in proportion to the scans you have already used, and you
            acknowledge this when you buy. Outside those jurisdictions we refund
            unused allowance on request within 14 days of purchase.
          </li>
          <li>
            We will give at least 30 days notice by email before any price
            increase takes effect for an existing subscription. You may cancel
            before it applies.
          </li>
          <li>
            Nothing here limits your non-waivable rights under consumer
            protection law where you live.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="live" title="7. Live scan">
        <p>
          Live scan is available on the Pro tier. During a live session, video
          frames stream in real time to our AI provider for analysis. We do not
          record or store the video. See the{" "}
          <Link
            href="/privacy#photos"
            className="text-foreground underline underline-offset-4"
          >
            Privacy policy
          </Link>{" "}
          for detail.
        </p>
        <p>
          Only scan your own face. Do not point the camera at another person,
          and do not run a session where others are in frame.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" title="8. Acceptable use">
        <p>You agree not to:</p>
        <LegalList>
          <li>
            Upload a photograph of anyone other than yourself, and never a
            photograph of a child.
          </li>
          <li>
            Use the service to obtain medical advice, or present its output as a
            medical opinion to anyone.
          </li>
          <li>
            Scrape, crawl, or bulk-download any part of the service, or access
            it by automated means other than a standard browser.
          </li>
          <li>
            Reverse engineer, decompile, or attempt to extract our prompts,
            models, or source code.
          </li>
          <li>
            Circumvent scan allowances, rate limits, authentication, or any
            other technical restriction.
          </li>
          <li>
            Attempt to make the assistant produce medical, harmful, or
            off-topic output, including by prompt injection.
          </li>
          <li>
            Resell, sublicense, or provide the service to third parties as your
            own.
          </li>
          <li>
            Upload malware, interfere with the service, or place unreasonable
            load on it.
          </li>
          <li>Use the service unlawfully or infringe anyone&apos;s rights.</li>
        </LegalList>
      </LegalSection>

      <LegalSection id="content" title="9. Your content and our rights">
        <LegalSubheading>What you upload stays yours</LegalSubheading>
        <p>
          You keep all rights in the photographs and information you upload. You
          grant us a limited, non-exclusive, worldwide licence to process them
          solely to provide the service to you: to analyse them, to generate
          your assessment, and to store the results you asked us to keep. That
          licence ends when you delete the content.
        </p>
        <p>
          <Term>
            We do not use your photographs, chats, or profile to train AI
            models.
          </Term>{" "}
          Not ours, and not anyone else&apos;s.
        </p>
        <LegalSubheading>Your reports</LegalSubheading>
        <p>
          Assessments and reports generated for you are yours to keep, download,
          and share as you wish.
        </p>
        <LegalSubheading>Our rights</LegalSubheading>
        <p>
          The service itself, including the software, design, prompts, product
          catalogue, and the Aurora Organics name and branding, remains ours.
          You get a personal, non-transferable, revocable right to use it under
          these terms, and nothing more.
        </p>
      </LegalSection>

      <LegalSection id="products" title="10. Product recommendations">
        <p>
          Recommendations are drawn from our own catalogue and are cosmetic
          suggestions, not prescriptions. We filter recommendations against the
          allergies in your profile, but that filter can only work with what you
          have told us and with the ingredient lists we hold.
        </p>
        <p>
          <Term>Always read the product label and patch test before use.</Term>{" "}
          Stop using anything that irritates your skin, and see a professional if
          a reaction persists. You are responsible for checking that a product
          suits you.
        </p>
      </LegalSection>

      <LegalSection id="termination" title="11. Suspension and termination">
        <p>
          You may close your account at any time from Privacy settings. Doing so
          deletes your data as described in the Privacy policy.
        </p>
        <p>
          We may suspend or terminate an account that breaches these terms.
          Other than where a breach is serious, unlawful, or poses a risk to
          others or to the service, we will give you notice and a reasonable
          chance to put it right first. You may appeal any decision by writing
          to{" "}
          <a
            href={`mailto:${LEGAL.contactEmail}`}
            className="text-foreground underline underline-offset-4"
          >
            {LEGAL.contactEmail}
          </a>
          .
        </p>
        <p>
          If we terminate your account other than for a breach by you, we will
          refund any unused paid allowance. Before any termination takes effect
          you will have a reasonable opportunity to export your data. Sections 9
          through 16 survive termination.
        </p>
      </LegalSection>

      <LegalSection id="warranty" title="12. Disclaimer of warranties">
        <p>
          To the fullest extent permitted by law, the service is provided{" "}
          <Term>as is</Term> and <Term>as available</Term>, without warranties
          of any kind, whether express, implied, or statutory. We specifically
          disclaim the implied warranties of merchantability, fitness for a
          particular purpose, and non-infringement.
        </p>
        <p>
          We do not warrant that the service will be uninterrupted, secure, or
          error free, or that any output will be accurate or suitable for you.
        </p>
        <p>
          If you are a consumer, this section does not limit any warranty or
          guarantee you have under law that cannot be excluded.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="13. Limitation of liability">
        <p>
          To the fullest extent permitted by law, we are not liable for
          indirect, incidental, special, consequential, or punitive damages, nor
          for loss of profits, revenue, data, or goodwill, arising from or
          connected to your use of the service.
        </p>
        <p>
          Our total aggregate liability arising from or connected to these terms
          or the service, whether in contract, tort, or otherwise, is limited to
          the greater of the amount you paid us in the twelve months before the
          claim arose, or fifty US dollars.
        </p>
        <p>
          Nothing in these terms excludes or limits our liability for death or
          personal injury caused by our negligence, for fraud or fraudulent
          misrepresentation, or for anything else that cannot lawfully be
          excluded or limited.
        </p>
      </LegalSection>

      <LegalSection id="indemnity" title="14. Indemnity">
        <p>
          You agree to indemnify us against claims, losses, and reasonable costs
          arising from your breach of these terms, from your unlawful use of the
          service, or from your uploading a photograph of another person without
          their permission. This does not apply to a consumer acting outside a
          business.
        </p>
      </LegalSection>

      <LegalSection id="law" title="15. Governing law and disputes">
        <p>
          These terms are governed by {LEGAL.governingLaw}, and{" "}
          {LEGAL.venue} have exclusive jurisdiction over any dispute.
        </p>
        <p>
          If you are a consumer resident elsewhere, this does not deprive you of
          the protection of the mandatory law of your country of residence, nor
          of the right to bring proceedings in your local courts.
        </p>
        <p>
          Before starting formal proceedings, please contact us at{" "}
          <a
            href={`mailto:${LEGAL.contactEmail}`}
            className="text-foreground underline underline-offset-4"
          >
            {LEGAL.contactEmail}
          </a>
          . Most problems are quicker to solve that way.
        </p>
      </LegalSection>

      <LegalSection id="general" title="16. General">
        <LegalList>
          <li>
            <Term>Severability.</Term> If any provision is unenforceable, the
            rest remains in force.
          </li>
          <li>
            <Term>No waiver.</Term> Not enforcing a right does not waive it.
          </li>
          <li>
            <Term>Assignment.</Term> You may not assign these terms. We may
            assign them to a successor in connection with a merger or sale, on
            notice to you.
          </li>
          <li>
            <Term>Notices.</Term> We contact you at the email on your account.
            You contact us at {LEGAL.contactEmail}.
          </li>
          <li>
            <Term>Force majeure.</Term> Neither party is liable for a failure
            caused by events beyond its reasonable control.
          </li>
          <li>
            <Term>Third-party services.</Term> Sign-in providers and our AI
            provider have their own terms, which apply to your use of them.
          </li>
          <li>
            <Term>Entire agreement.</Term> These terms and the Privacy policy
            are the whole agreement between us about the service.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection id="changes" title="17. Changes">
        <p>
          This is version {TERMS_OF_USE.version}, last updated{" "}
          {TERMS_OF_USE.updated}. We will give notice of material changes before
          they take effect. Continuing to use the service after that means you
          accept them. If you do not, close your account.
        </p>
      </LegalSection>
    </LegalPage>
  )
}
