import { getClimateRecommendations } from './climate';
import { getDoshaRecommendations } from './dosha';
import { type IngredientCatalogEntry } from './ingredients';
import { getLifestyleRecommendations } from './lifestyle';
import { findMatchingProducts, type ProductMatchResult, type ProductRepository, InMemoryProductRepository } from './products';
import { scoreSkinAnalysis, summarizeSeverity } from './scoring';
import { executeRecommendationRules } from './rules';
import type { ClimateData, DoshaProfile, Goal, LifestyleProfile, SkinAnalysis } from './types';

export interface RecommendationEngineInput {
  /** Skin analysis output generated by the AI scan or assessment. */
  skinAnalysis: SkinAnalysis;
  /** Environmental context that can influence the routine. */
  climate: ClimateData;
  /** Ingredient catalog used to select product ingredients. */
  ingredientDatabase?: IngredientCatalogEntry[];
  /** Dosha profile used for wellness-inspired adjustments. */
  dosha: DoshaProfile;
  /** Lifestyle data used for routine tuning. */
  lifestyle: LifestyleProfile;
  /** Product goals or desired outcomes. */
  goals: Goal[];
  /** Optional product repository for database-backed matching. */
  productRepository?: ProductRepository;
  /** Optional skin type for matching products. */
  skinType?: string;
  /** Optional country for product availability. */
  country?: string;
  /** Optional budget for product matching. */
  budget?: number;
}

export interface RecommendationEngineOutput {
  /** A short human-readable summary of the skin state. */
  skinSummary: string;
  /** A step-by-step skincare routine. */
  routine: string[];
  /** Ingredients recommended for the current profile. */
  recommendedIngredients: string[];
  /** Ingredients to avoid or limit for the current profile. */
  avoidIngredients: string[];
  /** Lifestyle guidance derived from everyday habits. */
  lifestyleAdvice: string[];
  /** Climate guidance derived from environmental context. */
  climateAdvice: string[];
  /** Ranked product matches from the repository. */
  recommendedProducts: ProductMatchResult[];
  /** Plain-language explanation of the final recommendation. */
  explanation: string;
  /** Confidence score from 0 to 100. */
  confidenceScore: number;
}

export class RecommendationEngine {
  private readonly productRepository: ProductRepository;

  constructor(productRepository?: ProductRepository) {
    this.productRepository = productRepository ?? new InMemoryProductRepository([]);
  }

  run(input: RecommendationEngineInput): RecommendationEngineOutput {
    const severityMap = scoreSkinAnalysis({
      hydration: input.skinAnalysis.hydration,
      sensitivity: input.skinAnalysis.sensitivity,
      redness: input.skinAnalysis.redness,
      pigmentation: input.skinAnalysis.pigmentation,
      barrier: input.skinAnalysis.barrier,
      texture: input.skinAnalysis.texture,
      oiliness: input.skinAnalysis.oiliness,
      dryness: input.skinAnalysis.dryness,
    });

    const severitySummary = summarizeSeverity({
      hydration: input.skinAnalysis.hydration,
      sensitivity: input.skinAnalysis.sensitivity,
      redness: input.skinAnalysis.redness,
      pigmentation: input.skinAnalysis.pigmentation,
      barrier: input.skinAnalysis.barrier,
      texture: input.skinAnalysis.texture,
      oiliness: input.skinAnalysis.oiliness,
      dryness: input.skinAnalysis.dryness,
    });

    const climateAdvice = getClimateRecommendations({
      temperature: input.climate.temperature,
      humidity: input.climate.humidity,
      uvIndex: input.climate.uvIndex,
      aqi: this.mapPollutionToAqi(input.climate.pollution),
    }).map((item) => `${item.label}: ${item.recommendation}`);

    const ruleExecution = executeRecommendationRules(input.skinAnalysis);
    const recommendedIngredients = ruleExecution.recommendedIngredients.length > 0 ? ruleExecution.recommendedIngredients : ['Ceramides', 'Niacinamide'];
    const avoidIngredients = ruleExecution.avoidIngredients;

    const doshaAdvice = getDoshaRecommendations({ dosha: this.toDoshaInput(input.dosha.primary) }).map(
      (item) => `${item.label}: ${item.recommendation}`,
    );

    const lifestyleAdvice = getLifestyleRecommendations({
      sleep: input.lifestyle.sleepHours,
      stress: input.lifestyle.stressLevel,
      water: input.lifestyle.hydrationHabits / 10,
      exercise: Math.round(input.lifestyle.sleepHours / 2),
      smoking: input.lifestyle.stressLevel > 70 ? 1 : 0,
      alcohol: 0,
      diet: input.goals.length > 0 ? 'balanced' : 'unknown',
    }).map((item) => `${item.label}: ${item.recommendation}`);

    const recommendedProducts = findMatchingProducts(
      {
        recommendedIngredients,
        skinType: input.skinType ?? 'normal',
        budget: input.budget ?? 100,
        country: input.country ?? 'US',
      },
      this.productRepository,
    );

    const routine = this.buildRoutine(recommendedIngredients, climateAdvice, doshaAdvice);
    const skinSummary = this.buildSkinSummary(severitySummary);
    const explanation = this.buildExplanation(severityMap, recommendedIngredients, climateAdvice, recommendedProducts, ruleExecution.rules.length);
    const confidenceScore = this.calculateConfidenceScore(severityMap, recommendedIngredients, recommendedProducts, climateAdvice);

    return {
      skinSummary,
      routine,
      recommendedIngredients,
      avoidIngredients,
      lifestyleAdvice,
      climateAdvice,
      recommendedProducts,
      explanation,
      confidenceScore,
    };
  }

  private buildRoutine(recommendedIngredients: string[], climateAdvice: string[], doshaAdvice: string[]): string[] {
    return [
      'Gentle cleanse with a non-stripping formula.',
      `Layer ${recommendedIngredients.slice(0, 2).join(' and ')} for support.`,
      'Apply sunscreen daily and reapply as needed.',
      ...climateAdvice.slice(0, 1),
      ...doshaAdvice.slice(0, 1),
    ];
  }

  private buildSkinSummary(severitySummary: Array<{ key: string; value: number; severity: string }>): string {
    const highest = [...severitySummary].sort((left, right) => right.value - left.value)[0];

    if (!highest) {
      return 'Balanced complexion with no obvious concerns.';
    }

    return `${highest.key} is the most prominent concern at ${highest.severity} severity.`;
  }

  private buildExplanation(
    severityMap: Record<string, string>,
    recommendedIngredients: string[],
    climateAdvice: string[],
    recommendedProducts: ProductMatchResult[],
    matchedRuleCount: number,
  ): string {
    const topConcern = Object.entries(severityMap).sort((left, right) => left[1].localeCompare(right[1]))[0]?.[0] ?? 'overall skin balance';

    return `The routine focuses on ${topConcern} with ${recommendedIngredients.join(', ')} support, ${matchedRuleCount} rule-based adjustment(s), climate guidance from ${climateAdvice.length} signal(s), and ${recommendedProducts.length} ranked product match(es).`;
  }

  private calculateConfidenceScore(
    severityMap: Record<string, string>,
    recommendedIngredients: string[],
    recommendedProducts: ProductMatchResult[],
    climateAdvice: string[],
  ): number {
    const highConcernCount = Object.values(severityMap).filter((value) => value === 'high' || value === 'severe').length;
    const base = 55 + highConcernCount * 5 + recommendedIngredients.length * 5 + recommendedProducts.length * 3 + climateAdvice.length * 2;

    return Math.min(100, Math.max(0, Math.round(base)));
  }

  private pickPrimaryConcern(severityMap: Record<string, string>): string {
    const priority = ['sensitivity', 'redness', 'hydration', 'pigmentation', 'oiliness', 'barrier', 'dryness'];
    const matched = priority.find((concern) => severityMap[concern] === 'high' || severityMap[concern] === 'severe');

    return matched ?? 'hydration';
  }

  private mapPollutionToAqi(pollution: ClimateData['pollution']): number {
    switch (pollution) {
      case 'high':
        return 120;
      case 'moderate':
        return 70;
      default:
        return 20;
    }
  }

  private toDoshaInput(dosha: DoshaProfile['primary']): 'vata' | 'pitta' | 'kapha' {
    if (dosha === 'vata' || dosha === 'pitta' || dosha === 'kapha') {
      return dosha;
    }

    return 'pitta';
  }
}
