export type Concern = 'hydration' | 'redness' | 'pigmentation' | 'barrier' | 'texture' | 'oil-control' | 'sensitivity' | 'oiliness';
export type Goal = 'glow' | 'calm' | 'repair' | 'protect' | 'balance';
export type ProductCategory = 'serum' | 'moisturizer' | 'cleanser' | 'treatment' | 'sunscreen';
export type Season = 'spring' | 'summer' | 'autumn' | 'winter';
export type DoshaType = 'vata' | 'pitta' | 'kapha' | 'tridoshic';

/**
 * Represents the skin analysis output captured from scanning or assessment.
 */
export interface SkinAnalysis {
  /** Overall skin condition score from 0 to 100. */
  overall: number;
  /** Estimated hydration level from 0 to 100. */
  hydration: number;
  /** Estimated sensitivity level from 0 to 100. */
  sensitivity: number;
  /** Estimated redness intensity from 0 to 100. */
  redness: number;
  /** Estimated pigmentation level from 0 to 100. */
  pigmentation: number;
  /** Estimated barrier strength from 0 to 100. */
  barrier: number;
  /** Estimated texture smoothness from 0 to 100. */
  texture: number;
  /** Estimated oiliness from 0 to 100. */
  oiliness: number;
  /** Estimated dryness from 0 to 100. */
  dryness: number;
}

/**
 * Represents a severity band used to describe how prominent a concern is.
 */
export interface SeverityScore {
  /** The concern name being scored. */
  concern: Concern;
  /** Severity from 0 to 100. */
  score: number;
  /** Human-readable severity classification. */
  label: 'low' | 'moderate' | 'high';
  /** Short explanation of why the concern received this score. */
  reason: string;
}

/**
 * Represents environmental context that can influence recommendation relevance.
 */
export interface ClimateData {
  /** Current temperature in Celsius. */
  temperature: number;
  /** Current humidity percentage. */
  humidity: number;
  /** Current UV index. */
  uvIndex: number;
  /** Current season for product suitability. */
  season: Season;
  /** General air quality band. */
  pollution: 'low' | 'moderate' | 'high';
  /** Human-readable location label. */
  location: string;
}

/**
 * Represents a single ingredient and its relevance to the recommendation engine.
 */
export interface Ingredient {
  /** Stable ingredient identifier. */
  id: string;
  /** Ingredient name as used in the formulation. */
  name: string;
  /** Primary skin concern the ingredient helps address. */
  concern: Concern;
  /** Suggested use strength from 0 to 100. */
  strength: number;
  /** Whether the ingredient is generally suitable for sensitive skin. */
  gentleForSensitiveSkin: boolean;
  /** Whether the ingredient helps strengthen the skin barrier. */
  supportsBarrier: boolean;
}

/**
 * Represents a user's dosha profile for wellness-oriented recommendation tuning.
 */
export interface DoshaProfile {
  /** Primary dosha classification. */
  primary: DoshaType;
  /** Secondary dosha classification. */
  secondary: DoshaType;
  /** Relative dosha score values. */
  scores: {
    /** Vata score from 0 to 100. */
    vata: number;
    /** Pitta score from 0 to 100. */
    pitta: number;
    /** Kapha score from 0 to 100. */
    kapha: number;
  };
}

/**
 * Represents a user's day-to-day lifestyle context that affects product suitability.
 */
export interface LifestyleProfile {
  /** Average nightly sleep hours. */
  sleepHours: number;
  /** User-reported stress intensity from 0 to 100. */
  stressLevel: number;
  /** Sunscreen usage frequency from 0 to 100. */
  sunscreenUse: number;
  /** Hydration habit consistency from 0 to 100. */
  hydrationHabits: number;
  /** Daily screen time in hours. */
  screenTimeHours: number;
}

/**
 * Represents a product available for recommendation.
 */
export interface Product {
  /** Stable product identifier. */
  id: string;
  /** Display name of the product. */
  name: string;
  /** Product category. */
  category: ProductCategory;
  /** Skin concerns this product is intended to support. */
  targets: Concern[];
  /** Ingredient identifiers used in the formulation. */
  ingredients: string[];
  /** Climate seasons where the product fits well. */
  climateFit: Season[];
  /** Lifestyle goals or habits the product supports. */
  lifestyleFit: Goal[];
  /** Whether the product is currently active for recommendation. */
  isActive: boolean;
}

/**
 * Represents a single product recommendation generated by the engine.
 */
export interface Recommendation {
  /** The recommended product. */
  product: Product;
  /** Final score from 0 to 1 indicating matching strength. */
  score: number;
  /** Ranking position in the final recommendation list. */
  rank: number;
  /** Human-readable reasons why this product was suggested. */
  reasons: string[];
  /** Scoring signals from each recommendation module. */
  signals: Array<{
    /** Module that produced the signal. */
    module: 'climate' | 'ingredients' | 'dosha' | 'lifestyle';
    /** Normalized signal score from 0 to 1. */
    score: number;
    /** Explanations for the signal. */
    reasons: string[];
  }>;
}

/**
 * Represents the final recommendation report returned to the application layer.
 */
export interface RecommendationSignal {
  /** The module that produced this signal. */
  module: 'climate' | 'ingredients' | 'dosha' | 'lifestyle';
  /** Normalized score from 0 to 1. */
  score: number;
  /** Explanation text produced for this signal. */
  reasons: string[];
}

export interface RecommendationReport {
  /** The user skin profile used for scoring. */
  skinAnalysis: SkinAnalysis;
  /** The climate context used for scoring. */
  climate: ClimateData;
  /** The user's dosha profile used for wellness-based scoring. */
  dosha: DoshaProfile;
  /** The user's lifestyle profile used for habit-based scoring. */
  lifestyle: LifestyleProfile;
  /** High-level severity findings extracted from the skin analysis. */
  severityScores: SeverityScore[];
  /** Final ranked recommendations. */
  recommendations: Recommendation[];
  /** Timestamp of report generation. */
  generatedAt: string;
}

export interface RecommendationInput {
  /** The skin assessment to use. */
  skin: SkinAnalysis;
  /** The lifestyle profile to use. */
  lifestyle: LifestyleProfile;
  /** The climate context to use. */
  climate: ClimateData;
  /** The user's dosha profile to use. */
  dosha: DoshaProfile;
  /** The goals the user wants to optimize for. */
  goals: Goal[];
  /** Optional product categories to limit results to. */
  preferredCategories?: ProductCategory[];
  /** Optional maximum number of recommendations to return. */
  limit?: number;
}

export interface RecommendationRules {
  /** Module weights used during final scoring. */
  weights: {
    /** Weight applied to climate relevance. */
    climate: number;
    /** Weight applied to ingredient relevance. */
    ingredients: number;
    /** Weight applied to dosha relevance. */
    dosha: number;
    /** Weight applied to lifestyle relevance. */
    lifestyle: number;
    /** Weight applied to direct product fit. */
    productFit: number;
  };
  /** Thresholds used for result interpretation. */
  thresholds: {
    /** Minimum score for a strong recommendation match. */
    strongMatch: number;
    /** Minimum score for a moderate recommendation match. */
    moderateMatch: number;
  };
}
